// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisclaimerModalController from "./disclaimer_modal_controller"
application.register("disclaimer-modal", DisclaimerModalController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import TogglePaymentDetailsController from "./toggle_payment_details_controller"
application.register("toggle-payment-details", TogglePaymentDetailsController)
