meta_product_name: "Pet Patron"
meta_title: "Pet Patron - Easily connect with shelters & support animals you love"
meta_description: "Easily connect with shelters & support animals you love"
meta_image: "fb-pic.png" # should exist in `app/assets/images/`
